### ISSUE TITLE
Player gets stuck on collider edges

### ISSUE THREAD

**Issue by CogEpitome** [bhatnathan/rot-world#56]

**Comment by bhatnathan** [comment]
It seems this is still happening occasionally. I think it happens more often when there are double blocks (as in two floor blocks in the same space) which mistakenly get added quite often using the level editor. I could be mistaken though. Regardless it seems to still happen here and there.

**Comment by CogEpitome** [comment]
@bhatnathan I made a fix in branch fix-edge-collision
It only works when gravity is down because I don't math
