### ISSUE TITLE
3D Models and textures

### ISSUE THREAD

**Issue by bhatnathan** [bhatnathan/rot-world#61]
- [x] Collectible
- [x] Player (texture)
- [x] Sliding door
- [x] Pushable block (texture)
- [x] Death Ground (should be a placeable block just as all the regular ground tiles)
- [x] Goal (stretch)

**Comment by bhatnathan** [comment]
Sorry accidentally closed this, still a few things left

**Comment by CogEpitome** [comment]
Making player texture stretch
