### ISSUE TITLE
Player can climb single unit blocks

### ISSUE THREAD

**Issue by bhatnathan** [bhatnathan/rot-world#7]
I think it would make sense if the player could climb up on blocks that are one unit high. That would lead to some interesting gameplay opportunities.

**Comment by bhatnathan** [comment]
Actually, we maybe don't need a climb, we could just have a jump instead, since that accomplishes everything a climb would do and would make jumping possible. Maybe there are some downsides, I'm not sure.

**Comment by CogEpitome** [comment]
From meeting: "If we have a Jump it might make 3D platforming difficult especially given the isometric view, whereas a climb doesn’t have the same problem.
Jumping is easier to program.
Idea: we start with jump and if we have time and feel it’s necessary then we could try to switch to a climb"
